name: Build and Deploy Next.js (Static Export)

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build Next.js (static export)
      - name: Build Next.js
        run: npm run build

      # 5️⃣ Проверяем, что папка out/ существует
      - name: Check export folder
        run: |
          echo "Current folder: $(pwd)"
          ls -la
          ls -la ./out/

      - name: Copy files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}       # SSH private key stored as a secret
          port: ${{ secrets.PORT }}         # optional, default is 22
          source: "./out/*"                # files/directories to copy
          target: "/public_html/"           # target directory on remote server



